"""Modify entity version 5

Revision ID: 5027387d973c
Revises: 656f34d608d7
Create Date: 2024-09-15 21:55:02.348608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5027387d973c'
down_revision: Union[str, None] = '656f34d608d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brands', ['name'])
    op.drop_column('brands', 'code')
    op.create_unique_constraint(None, 'categories', ['name'])
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'categories', type_='unique')
    op.add_column('brands', sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'brands', type_='unique')
    # ### end Alembic commands ###
