"""Modify user model and create base model

Revision ID: a72bbe510ee1
Revises: 3ed8875bca56
Create Date: 2024-09-09 20:38:06.648681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72bbe510ee1'
down_revision: Union[str, None] = '3ed8875bca56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_users_mobile', table_name='users')
    op.drop_column('users', 'name')
    op.drop_column('users', 'mobile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.create_index('ix_users_mobile', 'users', ['mobile'], unique=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'role')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
