"""Modify relationship product price in product model (version 6)

Revision ID: a9323daeea21
Revises: 2b8b0e3d1194
Create Date: 2024-09-19 01:23:20.539969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9323daeea21'
down_revision: Union[str, None] = '2b8b0e3d1194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
