"""Add fields to payment method

Revision ID: cf5a7170171c
Revises: 5027387d973c
Create Date: 2024-09-17 08:17:03.577938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5a7170171c'
down_revision: Union[str, None] = '5027387d973c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('description', sa.String(), nullable=True))
    op.add_column('payment_methods', sa.Column('type', sa.String(), nullable=False))
    op.add_column('payment_methods', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('payment_methods', sa.Column('transaction_fee', sa.Float(), nullable=True))
    op.add_column('payment_methods', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('payment_methods', sa.Column('provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_methods', 'provider')
    op.drop_column('payment_methods', 'currency')
    op.drop_column('payment_methods', 'transaction_fee')
    op.drop_column('payment_methods', 'is_active')
    op.drop_column('payment_methods', 'type')
    op.drop_column('payment_methods', 'description')
    # ### end Alembic commands ###
